### ISSUE TITLE
I ran the project test** file, but the operation returned without result

### ISSUE THREAD

**Issue by ithjz** [GoogleCloudPlatform/google-auth-library-python-oauthlib#15]
I ran the project test** file, but the operation returned without result

May I ask if there is a more detailed tutorial?

Did I make a configuration error?

{
    "installed": {
        "client_id": "806572844570-3iv5loac0v8rl01b3pia5apq92tvdtjb.apps.googleusercontent.com",
        "project_id": "magicdemo-179609",
        "auth_uri": "https://accounts.google.com/o/oauth2/auth",
        "token_uri": "https://accounts.google.com/o/oauth2/token",
        "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
        "redirect_uris": [
            "urn:ietf:wg:oauth:2.0:oob",
            "http://localhost"
        ]
    }
}

**Comment by jonparrott** [comment]
Hey @ithjz, I apologize for failing to give this attention when you filed it. I'm going to close due to inactivity, but if you're still there and need help please comment.
