### ISSUE TITLE
Credentials `id_token` is not verified, loaded, or parsed

### ISSUE THREAD

**Issue by ajaska** [GoogleCloudPlatform/google-auth-library-python-oauthlib#21]
Per the docs at https://developers.google.com/identity/sign-in/web/server-side-flow I would expect this functionality to be here.

It would be great if I could actually do something like

```python
userid = credentials.id_token['sub']
email = credentials.id_token['email']
```

**Comment by jonparrott** [comment]
#20 added this functionality, we just need to make a new release.

**Comment by ajaska** [comment]
Sorry, I don't think I was clear enough -- I was testing out the changes on master last night and if I'm not mistaken, id_token is available, but only as a string and not as a parsed and verified dict.

**Comment by jonparrott** [comment]
I see. That's correct behavior, see http://google-auth.readthedocs.io/en/latest/reference/google.oauth2.credentials.html#google.oauth2.credentials.Credentials.id_token

**Comment by ajaska** [comment]
Fair! Could you get the documentation at the link I share updated, then?

**Comment by ajaska** [comment]
I typed that way too fast... I meant "the documentation that I shared in the original issue comment" **

**Comment by jonparrott** [comment]
Yes, that documentation is for the older oauth2client, so it'll need to be updated to use google-auth anyway.

**Comment by jonparrott** [comment]
Closing this issue for now, moving the documentation issue to our internal tracker.
