### ISSUE TITLE
change from oauth2client

### ISSUE THREAD

**Issue by paulgholin** [GoogleCloudPlatform/google-auth-library-python-oauthlib#27]
Hi there,
I am new to oauth2 and changing oauth2client-related code to google_auth_oauthlib since the former is deprecated now.
Our private website compares a user's google+ id with our stored google+ ids to decide whether to give access. 
However **id_token** of the two are different types with different info and I don't find a way to access google+ id (gplus_id) using your Credentials object. The two versions of codes are basically as follows. Could you please help with this?

### oauth2client version
http://oauth2client.readthedocs.io/en/latest/_modules/oauth2client/client.html#OAuth2Credentials
```python
from oauth2client.client import flow_from_clientsecrets
@app.route('/connect', methods=['POST'])
def connect():
    code= request.data
    oauth_flow = flow_from_clientsecrets("client_secrets.json", scope='')
    oauth_flow.redirect_uri = 'postmessage'
    credentials = oauth_flow.step2_exchange(code)
    gplus_id = credentials.id_token['sub']
```

### google_auth_oauthlib trial version
http://google-auth.readthedocs.io/en/latest/_modules/google/oauth2/credentials.html#Credentials
```python
import google_auth_oauthlib.flow
@app.route('/connect', methods=['POST'])
def connect():
    code = request.data
    flow = google_auth_oauthlib.flow.Flow.from_client_secrets_file('client_secrets.json', scopes='')
    flow.redirect_uri = 'postmessage'
    flow.fetch_token(code=code)
    credentials = flow.credentials
```

Thank you.

**Comment by jonparrott** [comment]
Glad you got it figured out!
