### ISSUE TITLE
Use raw_input in example

### ISSUE THREAD

**Issue by y10h** [GoogleCloudPlatform/google-auth-library-python-oauthlib#30]
https://github.com/GoogleCloudPlatform/google-auth-library-python-oauthlib/blob/d6e922b8f816d4e2cc37455d94ae982ba19c541e/google_auth_oauthlib/flow.py#L39

Example uses input() which interprets input as a Python code, there should be raw_input() instead.

**Comment by theacodes** [comment]
Thanks for this bug report, but our samples are generally written for Python 3 where `raw_input` does not exist. Additionally, using `input` over `raw_input` in Python 2 is more of a concerned for server side apps, this sample runs on the user's machine.
