### ISSUE TITLE
file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth

### ISSUE THREAD

**Issue by timc13** [GoogleCloudPlatform/google-auth-library-python-oauthlib#32]
I'm getting this error all of a sudden on GAE.  It seems to be the same problem as https://github.com/googleapis/google-api-python-client/issues/325 - is there a workaround for this library?

**Comment by bdegley4789** [comment]
@timc13 how did you fix the error?

**Comment by timc13** [comment]
@bdegley4789 Upon further investigation I found that the problem is not with this library.  The warning  occurs in the `discovery.build()` call as described in https://github.com/googleapis/google-api-python-client/issues/325
