### ISSUE TITLE
How can I autopass Google Calendar API authorization on Android Things?

### ISSUE THREAD

**Issue by opengamer29** [GoogleCloudPlatform/google-auth-library-python-oauthlib#7]
As I see your library could be used for auto passing OAuth authorization on Android Things. It's used in this project for Google Assistant API - https://github.com/androidthings/sample-googleassistant.

I'm curious if it's possible to do the similar things for Google Calendar API authorizatoin. So in other words, is it possible to auto pass Google Calendar API authorization on Android Things device using your library?

Thanks!

**Comment by jonparrott** [comment]
Probably, you just need to change the scopes for calendar.

Maybe @proppy can provide some insight.

**Comment by proppy** [comment]
Yep, you can try to call the tool using the calendar scope:
```
google-oauthlib-tool --client-secrets client_secret_NNNN.json \
                     --credentials app/src/main/res/raw/credentials.json \
                     --scope https://www.googleapis.com/auth/calendar \
                     --save
```

**Comment by jonparrott** [comment]
(closing, but feel free to comment if you have further questions)
